DEL "document.aux"
DEL "document.bbl"
DEL "document.blg"
DEL "document.d"
DEL "document.fls"
DEL "document.ild"
DEL "document.ind"
DEL "document.toc"
DEL "document.lot"
DEL "document.lof"
DEL "document.idx"
DEL "document.out"
DEL "document.nlo"
DEL "document.nls"
DEL "document.pdf"
DEL "document.ps"
DEL "document.dvi"

pdflatex -interaction=nonstopmode "document.tex"
bibtex "document.aux"
makeindex "document.aux"
makeindex "document.idx"
makeindex "document.nlo" -s nomencl.ist -o "document".nls
pdflatex -interaction=nonstopmode "document.tex"
makeindex "document.nlo" -s nomencl.ist -o "document".nls
pdflatex -interaction=nonstopmode "document.tex"


DEL "document.aux"
DEL "document.bbl"
DEL "document.blg"
DEL "document.d"
DEL "document.fls"
DEL "document.ild"
DEL "document.ind"
DEL "document.toc"
DEL "document.lot"
DEL "document.lof"
DEL "document.idx"
DEL "document.out"
DEL "document.nlo"
DEL "document.nls"

document.pdf